lenguage: node_js
node_js: 
  - "6.9"
install:
  - npm install
cache:
  directories:
    - node_modules
script:
  - npm run code
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
